FROM node:20-alpine

# Diretório de trabalho no container
WORKDIR /api

COPY package.json yarn.lock ./

RUN yarn install

# Instala pacotes necessários para Chromium e Puppeteer
RUN apk add --no-cache \
  chromium \
  udev \
  ttf-freefont \
  harfbuzz \
  nss \
  freetype \
  poppler-utils \
  poppler-data

# Define o caminho executável para Puppeteer
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY . .

EXPOSE 3000

CMD ["yarn", "start:dev"]
